---
title: "RWorksheet_Subosa#4a.Rmd"
author: "Gian Adree Subosa"
date: "2024-10-18"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1. Data for shoe size and height
```{r}
# Create the data frame
shoe_size <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 8.5, 10.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 8.5, 8.5, 10.5, 11.0, 9.0, 13.0)
height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 69.0, 71.0, 72.0, 64.0, 67.0, 74.5, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 69.0, 73.0, 69.0, 70.0)
gender <- c('F', 'F', 'F', 'F', 'M', 'F', 'F', 'M', 'M', 'F', 'F', 'M', 'M', 'M', 'M', 'M', 'F', 'F', 'M', 'F', 'F', 'M', 'M', 'M', 'M', 'M')

df <- data.frame(Shoe_Size = shoe_size, Height = height, Gender = gender)
summary(df)

#a.) Describe the data.
#       The data contains information about the shoe size, height and gender. The data indicates that males tend to have larger shoe sizes and greater heights compared to females, as reflected in the overall summary. 
```

```{r}
#b.) Create a subset
male_subset <- subset(df, Gender == 'M')
female_subset <- subset(df, Gender == 'F')
print(male_subset)
print(female_subset)
```

```{r}
#c.) Find the mean of shoe size and height of the respondents
mean_shoe_size <- mean(df$Shoe_Size)
mean_height <- mean(df$Height)
print(mean_shoe_size)
print(mean_height)
```

```{r}
#d.) Is there a relationship between shoe size and height? Why?
correlation_data <- cor(df$Shoe_Size, df$Height)
print(correlation_data)

# A correlation of 0.7750242 indicates a strong positive relationship between shoe size and height. This means that, generally, as shoe size increases, height also increases among the respondents.
```

#2. Construct character vector months to a factor with factor() and assign the result to factor_months_vector
```{r}
months_vector <- c("March", "April", "January", "November", "January", "September", "October", "September", "November", "August", "January", "November", "November", "February", "May", "August", "July", "December", "August", "August", "September", "November", "February", "April")
factor_months_vector <- factor(months_vector)
print(factor_months_vector)
```

#3. Check the summary() of the months_vector and factor_months_vector
```{r}
summary(months_vector)
summary(factor_months_vector)

# Are they both equally useful in this case?
#         The factor vector is more beneficial in this scenario because it provides a clear split of the number of occurrences for each month, making data analysis and interpretation easier. In contrast, the character vector lacks the ability to summarize the frequency of unique values. As a result, turning the months to a factor with factor() is more suited for evaluating categorical data such as month names.
```

#4. Create a vector for direction and frequency and factor below
```{r}
direction <- c("East", "West", "North")
frequency <- c(1, 4, 3)

direction_data <- data.frame(Direction = direction, Frequency = frequency)

factor_data <- factor(direction_data$Direction)

new_order_data <- factor(factor_data, levels = c("East", "West", "North"))
print(new_order_data)
```

#5. Enter the data below in Excel with file name = import_march.csv
```{r}
#a.) Import the excel file into the Environment Pane using read.table() function
data_table <- read.table("import_march.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
print(data_table)
```
```{r}
#b.) View the dataset
View(data_table)
```