---
title: "RWorksheet_Subosa#4b.Rmd"
author: "Gian Adree Subosa"
date: "2024-10-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1. Using the for loop, create an R script that will display a 5x5 matrix
```{r}
vectorA <- c(1, 2, 3, 4, 5)
matrix5x5 <- matrix(0, nrow = 5, ncol = 5)

for (i in 1:5) {
  for (j in 1:5) {
    matrix5x5[i, j] <- abs(vectorA[i] - vectorA[j])
  }
}

print(matrix5x5)
```

#2. Print the string "*" using for() function
```{r}
asteris <- 5

for(i in 1:asteris) {
  cat(rep("*", i), "\n")
}
```

#3. Fibonacci Sequence
```{r}
val <- 25

a <- 0
b <- 1

if (val <= a) {
  cat(a, " ")
}
if (val <= b) {
  cat(b, " ")
}

repeat {
  next_number <- a + b
  if (next_number > 500) {
    break
  }
  if (next_number >= val) {
    cat(next_number, " ")
  }
  
  a <- b
  b <- next_number
}
```

#4. Import the dataset
```{r}
#a.) Import the file. Display the first 6 rows of the dataset
my_data <- read.csv("shoe_height_gender_data.csv")
head(my_data)
```

```{r}
#b.) Create a subset for gender(female and male)
m_sub <- subset(my_data, Gender == "M")
f_sub <- subset(my_data, Gender == "F")

num_Male <- nrow(m_sub)
num_Female <- nrow(f_sub)

cat("Number of Male observations: ",num_Male, "\n")
cat("Number of Female observations: ",num_Female, "\n")
```

```{r}
#c.) Create a graph for the number of males and females for Household Data
male_count <- nrow(subset(my_data, Gender == "M"))
female_count <- nrow(subset(my_data, Gender == "F"))

gender_count <- data.frame(
  Gender = c("Male", "Female"),
  Count = c(num_Male, num_Female)
)

barplot(
  height = gender_count$Count,
  names.arg = gender_count$Gender,
  col = c("blue", "pink"),
  main = "Number of Males and Females in Household Data",
  xlab = "Gender",
  ylab = "Number of Observations",
  legend.text = TRUE,
  beside = TRUE
)
legend("topright", legend = gender_count$Gender, fill = c("blue", "pink"))
```

#5. Monthly income of DeLaCruz family
```{r}
# Data for Dela Cruz family's monthly income distribution
expenses <- c(60, 10, 5, 25)
labels <- c("Food", "Electricity", "Savings", "Miscellaneous")

#a.) Create a pie chart that will include labels in percentage
percentages <- round(expenses / sum(expenses) * 100, 1)
labels_with_percentages <- paste(labels, percentages, "%", sep = " ")
colors <- c("lightblue", "lightgreen", "red", "yellow")

pie(
  expenses,
  labels = labels_with_percentages,
  col = colors,
  main = "Monthly Income Distribution of Dela Cruz Family"
)
legend("topright", legend = labels, fill = colors)
```

#6. The iris dataset
```{r}
#a.) Check for the structure of the dataset using the str() function
data(iris)
str(iris)
#The dataset shows its dimensions which are 150 observations and 5 variables.
```

```{r}
#b.) Create an R object that will contain the mean of the sepal.length, sepal.width,petal.length,and petal.width
mean_values <- colMeans(iris[, 1:4])
print(mean_values)
```

```{r}
#c.) Create a pie chart for the Species distribution
data(iris)
species_counts <- table(iris$Species)
colors <- c("skyblue", "lightgreen", "salmon")

pie(species_counts,
    main = "Species Distribution in Iris Dataset",
    col = colors,
    labels = paste(names(species_counts), "(", species_counts, ")", sep = "")
)

legend("topright", 
       legend = names(species_counts), 
       fill = colors,
       title = "Species")
```

```{r}
#d.) Subset the species into setosa, versicolor, and virginica
data(iris)
setosa <- subset(iris, Species == "setosa")
versicolor <- subset(iris, Species == "versicolor")
virginica <- subset(iris, Species == "virginica")

tail(setosa, 6)
tail(versicolor, 6)
tail(virginica, 6)
```

```{r}
#e.) Create a scatterplot
data(iris)
iris$Species <- as.factor(iris$Species)
species_colors <- c("setosa" = "orange", "versicolor" = "blue", "virginica" = "green")
species_symbols <- c("setosa" = 16, "versicolor" = 17, "virginica" = 18)

plot(iris$Sepal.Length, iris$Sepal.Width,
     main = "Iris Dataset",
     sub = "Sepal Width and Length",
     xlab = "Sepal Length",
     ylab = "Sepal Width",
     col = species_colors[iris$Species],
     pch = species_symbols[iris$Species])

legend("topright",
       legend = levels(iris$Species),
       col = c("orange", "blue", "green"),
       pch = c(16, 17, 18),
       title = "Species")
```

```{r}
#f.) Interpret the result

#This scatterplot clearly illustrates the differences in sepal diameters between the three iris flower species. Setosa is easily identified by its wider and shorter sepals, but virginica and versicolor share some similarities, with virginica having the longest sepals overall. The natural grouping of species according to their sepal traits can be better understood with the help of this depiction.
```

#7. Basic Cleaning and Transformation of Objects
```{r}
#a.) Rename the white and black variants by using gsub() function
data_frame <- read_excel("alexa_file.xlsx")
head(data_frame)
```

```{r}
#b.) Get the total number of each variations and save it into another object
count_var <- data_frame %>%
  count(variation)
print(count_var)
save(count_var, file = "variations.RData")
```

```{r}
#c.) From the variations.RData, create a barplot()
barplot(
  count_var$n,                         
  names.arg = count_var$variation,     
  main = "Count of Each Variation",           
  xlab = "Variation",                         
  ylab = "Total Count",                       
  col = rainbow(length(count_var$n)),  
  las = 2                                     
)
```

```{r}
#d.) Create a barplot() for the black and white variations
black_and_white <- subset(count_var, grepl("Black|White", count_var$variation))

barplot(
  black_and_white$n,
  names.arg = black_and_white$variation,
  main = "Count of Black and White Variations",
  xlab = "Variation",
  ylab = "Total Count",
  col = c("black", "gray"),                   
  beside = TRUE                               
)

```



