---
title: "RWorksheet_Subosa#2.R"
author: "Gian Adree Subosa"
date: "2024-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#1. Create a vector using : operator
```{r}
#a.) Sequence from -5 to 5
seq1 <- c(-5:5)
print(seq1)
#The output is: [1] -5 -4 -3 -2 -1  0  1  2  3  4  5

#b.) What will be the value of x?
x <- 1:7
print(x)
#The output is: [1] 1 2 3 4 5 6 7
```
#2. Create a vector using seq() function
```{r}
vector1 <- seq(1, 3, by = 0.2)
print(vector1)
#The output is: [1] 1.0 1.2 1.4 1.6 1.8 2.0 2.2 2.4 2.6 2.8 3.0
```
#3. Ages of the factory workers
```{r}
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,
24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
18)

#a.) Access the third element
ages[3]
#The output is: [1] 22

#b.) Access second and fourth element
ages[c(2, 4)]
#The output is: [1] 28 36

#c.) Access all but the fourth and 12th element is not included
ages[c(-4, -12)]
#The output is: [1] 34 28 22 27 18 52 39 42 29 35 27 22 37 34 19 20 57 49 50 37 46 25 17 37 [25] 43 53 41 51 35 24 33 41 53 40 18 44 38 41 48 27 39 19 30 61 54 58 26 18
```
#4. Names vector
```{r}
x <- c("first" = 3, "second" = 0, "third" = 9)

#a.) Print the results. 
print(names(x))
#The output of this vector is: [1] "first"  "second" "third" 

#b.) Access first and third. Write the code and its output
x[c("first", "third")]
#The output is : first third 
#                    3     9 
#The output looks like a table, wherein the first and the third are the columns or the variables while the values 3 and 9 are the inputs of an observation (rows). 
```
#5. Create a sequence x from -3:2
```{r}
x <- seq(-3:2)
print(x)
#The output is: [1] 1 2 3 4 5 6

#a.) Modify second element and change it to 0
x[2] <- 0
x
#The second element which is 2 was change to 0.

#b.) Write the code and its output 
x <- seq(-3:2)
x[2] <- 0
print(x)
#The output is: [1] 1 0 3 4 5 6
```
#6. Data of diesel fuels purchased by Mr. Cruz
```{r}
months = c("Jan", "Feb", "March", "Apr", "May", "June")
price_per_liter = c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase_quantity = c(25, 30, 40, 50, 10, 45)

#a.) Create a data frame for month, price per liter, and purchase-quantity. Write the R scripts and its output
da_fr <- data.frame(Month = months, PricePerLiter = price_per_liter, PurchaseQuantity = purchase_quantity)
print(da_fr)

#b.) Average fuel expenditure of Mr. Cruz from Jan to June
aver_fuel <- weighted.mean(da_fr$Price_Per_Liter, da_fr$Purchase_Quantity)
print(paste(aver_fuel))
```
#7. Built-in Data Sets
```{r}
#a.) Type "rivers" and create a vector data with 7 elements
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), sd(rivers), min(rivers), max(rivers))
print(data)

#b.) What are the results
#The results are the length, sum, mean, median, variance, standard deviation, minimum and the maximum of rivers
#c.) Write the code and its outputs
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), sd(rivers), min(rivers), max(rivers))
print(data)
#The outputs are: [1]    141.0000  83357.0000    591.1844    425.0000 243908.4086    493.8708
#                 [7]    135.0000   3710.0000
```
#8. Forbes Ranking
```{r}
#a.) Create vectors according to the table
powerRanking <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
celebrityName <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stem", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K. Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Lenon", "Celine Dion", "Kobe Bryant")
pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)

celeb <- data.frame(PowerRanking = powerRanking, Celebrity = celebrityName, Pay = pay)
print(celeb)

#b.) Modify power ranking and pay of J.K. Rowling and change power ranking to 15 and pay to 90
powerRanking[19] <- 15
pay[75] <- 90
celeb <- data.frame(PowerRanking = powerRanking, Celebrity = celebrityName, Pay = pay)
print(celeb)

#c.) Create an excel file
write.csv(celeb, file = "PowerRanking.csv", row.names = FALSE)
importedData <- read.csv("PowerRanking.csv")
print(importedData)

#d.) Access the rows 10 to 20 
ranksData <- celeb[10:20, ]
save(ranksData, file = "Ranks.Data")
print(ranksData)

#e.) It displays the rows 10 to 20 in a separate file.
```
#9. Download the Hotels-Vienna
```{r}
#a.) Import the excel file to your RStudio
library(readxl)
hotelsVienna_Data <- read_excel("hotels-vienna.xlsx")
print(hotelsVienna_Data)

#b.) How many dimensions does the dataset have?
dimensions <- dim(hotelsVienna_Data)
print(dimensions)

#c.) Select columns
class(hotelsVienna_Data)
selection <- hotelsVienna_Data[,c("country", "neighbourhood", "price", "stars", "accommodation_type", "rating")]
print(selection)

#d.) Save the data as **new.RData
save(selection, file = "new.RData")
print(head(selection))
print(tail(selection))

#e.) Display the first six rows and last six rows of the new.RData
load("new.RData")
print(head(selection))
print(tail(selection))
```
#10. Create a list of ten (10) vegetables you eat during your lifetime
```{r}
#a.) Write the code and its output
vegetables <- c("Raddish", "Cauliflower", "Carrot", "Legumes", "Tomato", "Onion", "Eggplant", "Squash", "Capsicum", "Papaya")
print(vegetables)

#b.) Add two additional vegetables after the last vegetables
vegetables <- c(vegetables, "Broccoli", "Turnip")
print(vegetables)

#c.) Add 4 additional vegetables after index 5. How many data points does your vegetable list have? What is the R script and its output?
vegetables <- append(vegetables, c("Potato", "Mushroom", "Garlic", "Peas"))
print(vegetables)
vegetables_dp <- length(vegetables)
print(vegetables_dp)

#d.) Remove the vegetables in index 5, 10, and 15
vegetables <- vegetables[-c(5, 10, 15)]
print(vegetables)
left <- length(vegetables)
print(left)
```