---
title: "RWorksheet_Subosa#3a.Rmd"
author: "Gian Adree Subosa"
date: "2024-10-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1. LETTER Vector
```{r}
#a.) Produce a vector that contains the first eleven letters
eleven_l <- LETTERS[1:11]
print(eleven_l)
```

```{r}
#b.) Produce a vector that contains the odd numbered letters
odd_letters <- LETTERS[seq(1, 26, by = 2)]
print(odd_letters)
```

```{r}
#.c) Produce vectors that contains the vowels
vowels <- LETTERS[c(1, 5, 9, 15, 21)]
print(vowels)
```

```{r}
#d.) Produce a vector that contains the last 5 lowercase letters
last5letters <- letters[22:26]
print(last5letters)
```

```{r}
#e.) Produce a vector that contains letters between 15 to 24 letters in lowercase
lowercase <- letters[15:24]
print(lowercase)
```

#2. City Temperature
```{r}
#a.) Characters of the city
cities <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
print(cities)
```

```{r}
#b.) Vectors of the temperature
temp <- c(42, 39, 34, 34, 30, 27)
print(temp)
```

```{r}
#c.) Data frame to combine the city and the temp
citytemp <- data.frame(City = cities, Tempreture = temp)
print(citytemp)
```

```{r}
#d.) Rename the columns using names() function
names(citytemp) <- c("City", "Temperature")
print(citytemp)
```

```{r}
#e.) Print the structure using str()
str(citytemp)
#displays the output of citytemp
```

```{r}
#f.) What is the output of row 3 and row 4
(citytemp[3:4, ])
#displays the observations in rows 3 and 4
```

```{r}
#g.) Display the city with highest temperature and the city with the lowest temperature.
(citytemp[which.max(citytemp$Temp), ])
(citytemp[which.min(citytemp$Temp), ])
```

#3. Using Matrices
#Create a matrix of one to eight and eleven to fourteen with four columns and three rows
```{r}
#a.) What will be the R code for the #2 question and its result?
matrix1 <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4, byrow = TRUE)
print(matrix1)
#It displays the output has 3 rows and 4 columns with values from 1 to 8 and 11 to 14
```

```{r}
#b.) Multiply the matrix by two. What is its R code and its result?
matrix_multiply <- matrix1 * 2
print(matrix_multiply)
#The output's values has been multiplied to 2
```

```{r}
#c.) What is the content of row 2? What is its R code?
row_matrix <- matrix1[2, ]
print(row_matrix)
```

```{r}
#d.) What will be the R code if you want to display the column 3 and column 4 in row 1 and row 2? What is its output?
mtrx <- matrix1[1:2, 3:4]
print(mtrx)
```

```{r}
#e.) What is the R code is you want to display only the columns in 2 and 3, row 3? What is its output?
nmtrx <- matrix1[3, 2:3]
print(nmtrx)
```

```{r}
#f.) What is the R code is you want to display only the columns 4? What is its output?
col4 <- matrix1[ , 4]
print(col4)
```

```{r}
#g.) Name the rows as isa, dalawa, tatlo and columns as uno, dos, tres, quatro for the matrix that was created in b. What is its R code and corresponding output?
rownames(matrix_multiply) <- c("isa", "dalawa", "tatlo")
colnames(matrix_multiply) <- c("uno", "dos", "tres", "quatro")
print(matrix_multiply)
```

```{r}
#h.) New dimensions should have 2 columns and 6 rows
dim(matrix1) <- c(6, 2)
print(matrix1)
```

#4. Using Arrays
```{r}
#a.) Create an array with the values repeated twice
values <- rep(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1), 2)
# Create a three-dimensional array with 4 columns, 2 rows, and calculate the depth
array_1 <- array(values, dim = c(2, 4, 3))
print(array_1)
```

```{r}
#b.) How many dimensions do your array have?
dim(array_1)
```

```{r}
#c.) Assign row and column names
dimnames(array_1) <- list(c("a", "b"), c("A", "B", "C", "D"), 
                          c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array"))
print(array_1)
```